services:
  db:
    image: postgres
    container_name: rlt-db
    restart: always
    shm_size: 128mb
    env_file:
      - ".env"
    volumes:
      - ".database/dumps/:/docker-entrypoint-initdb.d:ro"
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    image: adminer
    container_name: rlt-adminer
    restart: always
    ports:
      - 8080:8080


  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: rlt-api
    volumes:
      - ./api/app:/app/app
      - ./database:/database
    env_file:
      - ".env"
    environment:
      POSTGRES_HOST: db
    expose:
      - 80

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: rlt-frontend
    expose:
      - 80

  nginx:
    image: nginx:alpine
    container_name: rlt-nginx
    restart: always
    depends_on:
      - api
      - frontend
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  pgdata: